{
  "poll_interval_seconds": 300,
  "sources": [
    { "name": "bbc", "rss_url": "https://feeds.bbci.co.uk/news/rss.xml", "enabled": true },
    { "name": "lenta", "rss_url": "https://lenta.ru/rss", "enabled": true },
    { "name": "rbc", "rss_url": "https://rssexport.rbc.ru/rbcnews/news/20/full.rss", "enabled": false },
    { "name": "ria", "rss_url": "https://ria.ru/export/rss2/index.xml", "enabled": true },
    { "name": "tass", "rss_url": "https://tass.ru/rss/v2.xml", "enabled": true },
    { "name": "interfax", "rss_url": "https://www.interfax.ru/rss.asp", "enabled": true },
    { "name": "meduza", "rss_url": "https://meduza.io/rss/all", "enabled": true },
    { "name": "rt_ru", "rss_url": "https://russian.rt.com/rss", "enabled": true },
    { "name": "habr", "rss_url": "https://habr.com/ru/rss/all/all/?fl=ru", "enabled": true },
    { "name": "village", "rss_url": "https://www.the-village.ru/rss", "enabled": true },
    { "name": "bbc_ru", "rss_url": "http://feeds.bbci.co.uk/russian/rss.xml", "enabled": true },
    { "name": "dw_ru", "rss_url": "https://rss.dw.com/russian", "enabled": false },
    { "name": "reuters_top", "rss_url": "https://feeds.reuters.com/reuters/topNews", "enabled": false },
    { "name": "ap_top", "rss_url": "https://feeds.apnews.com/apf-topnews", "enabled": false },
    { "name": "nyt_world", "rss_url": "https://rss.nytimes.com/services/xml/rss/nyt/World.xml", "enabled": true },
    { "name": "ars", "rss_url": "http://feeds.arstechnica.com/arstechnica/index/", "enabled": true },
    { "name": "hn_front", "rss_url": "https://hnrss.org/frontpage", "enabled": false },
    {
      "name": "gnews_ru",
      "type": "gnews",
      "api_token": "YOUR_GNEWS_TOKEN",
      "enabled": false,
      "params": { "lang": "ru", "topic": "world", "max": 50 }
    }
  ]
}
